site_name: Герману нехуй делать
site_description: Сборник конспектов, работ и проектов
site_author: Ямщиков Герман М3233

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - scheme: slate
      primary: black
      accent: blue

nav:
  - Главная: index.md

  - Математика:
      - Обзор: math/index.md

  - Физика:
      - Обзор: physics/index.md

  - Алгоритмы:
      - Обзор: algo/index.md

  - Программирование:
      - Обзор: programming/index.md

  - Проекты:
      - Обзор: projects/index.md

  - Интересы:
      - Обзор: interests/index.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true

  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
